name: Test FerrisWheel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_ferriswheel:

    strategy:
      fail-fast: false
      matrix:
        python: [3.8.x, 3.9.x, 3.10.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install FerrisWheel
      run: python -m pip install .

    - name: Run tests
      run: python tests/test_ferriswheel.py
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
      
