name: Test FerrisWheel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_ferriswheel:

    strategy:
      fail-fast: false
      matrix:
        python: [3.8.x, 3.9.x, 3.10.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    
    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -e .

    - name: Install FerrisWheel
      run: python -m pip install -U .

    - name: Run tests
      run: python tests/test_ferriswheel.py
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
        TOKEN: ${{ secrets.TOKEN }}